kind = "web"
previewPath = "/"
title = "Nuatis POS"
version = "1.0.0"
id = "artifacts/nuatis-pos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22908

[services.development]
run = "pnpm --filter @workspace/nuatis-pos run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nuatis-pos", "run", "build" ]
publicDir = "artifacts/nuatis-pos/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22908"
BASE_PATH = "/"
